### ISSUE TITLE
FileNotFoundError: [Errno 2] Results/helpdesk/EventPredictor_parameters_helpdesk_weighted_0.0001_run0.pt'

### ISSUE THREAD

**Issue by Akshay1010567** [ishwarvenugopal/GCN-ProcessPrediction#1]
Hello,

while running model and file: GCN-ProcessPrediction/Evaluate_Models/Event_Quartiles/EventQuartiles_EventPredictor_(GCN).ipynb and all other similar .ipynb files, I got the error model not found. Can you please explain, how do you saved that model file(/....pt) and load it? 

Thank you for all the codes and work, waiting for your reply.

**Comment by ascherp** [comment]
Hi

I suggest you first train the model using the train script. Subsequently 
you can execute the evaluation. The models themselves are not in the git.

Best

**Comment by Akshay1010567** [comment]
Thank you for the reply @ascherp 

I have tried but could not find the training script. For example,  I would like to run the file [EventQuartiles_EventPredictor_(GCN).ipynb](https://github.com/ishwarvenugopal/GCN-ProcessPrediction/blob/master/Evaluate_Models/Event_Quartiles/EventQuartiles_EventPredictor_(GCN).ipynb)   and also other, so which specific training script should I run first????  Please let me know the location of the train script or share the link to the file. 

Thanks and waiting for your answer

**Comment by ishwarvenugopal** [comment]
Hi @Akshay1010567 , the training scripts are the files you see in the repository outside the folders (i.e the following files: GCN_EventPredictor_(Training).ipynb, GCN_TimePredictor_(Training).ipynb, MLP_EventPredictor_(Training).ipynb and MLP_TimePredictor_(Training).ipynb).

You can refer to the README for detailed instructions.

**Comment by Akshay1010567** [comment]
Thank you @ishwarvenugopal. This solved my issue.
